language: python

python:
  - "3.5"

install:
  - pip install -r requirements.txt -r test-requirements.txt
  # - pip install .

script: 
  - py.test --cov --cov-config .coveragerc --cov-report html
  #- coverage run py.test

after_success:
  - coverage report
  - coveralls


